service:
  name: resource-hosting

plugins:
  - '@hewmen/serverless-plugin-typescript'  
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.bridged.cc
    basePath: 'hosting'
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

resource:
  s3bucket:
    Type: S3::Bucket
    Properties:
      BucketName: static-hosting


package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}