service:
  name: resource-hosting

plugins:
  - '@hewmen/serverless-plugin-typescript'  
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: resources.bridged.cc
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
      binaryMediaTypes:
          - 'multipart/form-data'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::reflect-icons/*"


package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true