# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service:
  name: cors

frameworkVersion: '2'

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.cors
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: /{url}
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript
