# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service:
  name: cors

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
    
functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - '@hewmen/serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
