# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

service: cors

custom:
  customDomain:
    domainName: cors.bridged.cc
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
  serverless-offline:
    httpPort: 4012

provider:
  name: aws
  memorySize: 128
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
  region: us-west-1

# The `functions` block defines what code to deploy
functions:
  api:
    handler: src/index.handler
    maximumEventAge: 60
    maximumRetryAttempts: 0
    timeout: 12
    events:
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /
          method: get

plugins:
  - "@hewmen/serverless-plugin-typescript"
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager
