service:
  name: resource-hosting

plugins:
  - '@hewmen/serverless-plugin-typescript'  
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: hosting.bridged.cc
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
  serverless-offline:
    httpPort: 4005

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  apiGateway:
      binaryMediaTypes:
          - 'multipart/form-data'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::resource-hosting/*"

resource:
  s3bucket:
    Type: S3::Bucket
    Properties:
      BucketName: resource-hosting


package:
  individually: true

functions:
  main:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true